version: 2.1

orbs:
  terraform: circleci/terraform@3.0.0

executors:
  base_image:
    docker:
      - image: cimg/base:stable

jobs:
  terraform_validate_networking:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init
          path: networking/
      - terraform/validate:
          path: networking/
      - terraform/fmt:
          path: networking/
      - terraform/plan:
          path: networking/

workflows:
  iac_networking:
    jobs:
      - terraform_validate_networking
