version: 2.1

orbs:
  terraform: circleci/terraform@3.0.0

jobs:
  iac_networking_validate:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: networking
      - terraform/fmt:
          path: networking
      - terraform/validate:
          path: networking
      - terraform/plan:
          path: networking
      - run:
          name: Check Terraform Version
          command: terraform -v

  iac_networking_deploy:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: networking
      - run:
          name: Conditional Apply
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
               terraform -chdir=networking plan -detailed-exitcode
               if [ $? -eq 2 ]
               then
                 terraform apply -auto-approve
               fi
            fi

  iac_compute_validate:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: compute
      - terraform/fmt:
          path: compute
      - terraform/validate:
          path: compute
      - terraform/plan:
          path: compute
      - run:
          name: Check Terraform Version
          command: |
            terraform -v
            echo ${PRI_01}
            echo ${PRI_02}

  iac_compute_deploy:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: compute
      - run:
          name: Conditional Apply
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
               terraform -chdir=compute plan -detailed-exitcode
               if [ $? -eq 2 ]
               then
                 terraform apply -auto-approve
               fi
            fi

  iac_data_validate:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: data
      - terraform/fmt:
          path: data
      - terraform/validate:
          path: data
      - terraform/plan:
          path: data
      - run:
          name: Check Terraform Version
          command: terraform -v

  iac_data_deploy:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: data
      - run:
          name: Conditional Apply
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
               terraform -chdir=data plan -detailed-exitcode
               if [ $? -eq 2 ]
               then
                 terraform apply -auto-approve
               fi
            fi

  iac_analytics_validate:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: analytics
      - terraform/fmt:
          path: analytics
      - terraform/validate:
          path: analytics
      - terraform/plan:
          path: analytics
      - run:
          name: Check Terraform Version
          command: terraform -v

  iac_analytics_deploy:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: analytics
      - run:
          name: Conditional Apply
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
               terraform -chdir=analytics plan -detailed-exitcode
               if [ $? -eq 2 ]
               then
                 terraform apply -auto-approve
               fi
            fi

workflows:
  validate_infrastructure:
    jobs:
      - iac_networking_validate:
          context: terraform
          filters:
            branches:
              only:
                - /^feature.*/
                - develop
      - iac_compute_validate:
           context:
             - terraform
             - aws_keypair
           filters:
             branches:
               only:
                 - /^feature.*/
                 - develop
           requires:
             - iac_networking_validate
      - iac_data_validate:
           context: terraform
           filters:
             branches:
               only:
                 - /^feature.*/
                 - develop
           requires:
             - iac_compute_validate
      - iac_analytics_validate:
           context: terraform
           filters:
             branches:
               only:
                 - /^feature.*/
                 - develop
           requires:
             - iac_data_validate

  deploy_infrastructure:
    jobs:
      - iac_networking_deploy:
          context: terraform
          filters:
            branches:
              only:
                - master
      - iac_compute_deploy:
          context:
            - terraform
            - aws_keypair
          filters:
            branches:
              only:
                - master
          requires:
            - iac_networking_deploy
