version: 2.1

orbs:
  terraform: circleci/terraform@3.0.0

jobs:
  iac_networking:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: networking
      - terraform/fmt:
          path: networking
      - terraform/validate:
          path: networking
      - terraform/plan:
          path: networking
      - run:
          name: Check Terraform Version
          command: terraform -v

workflows:
  deploy_infrastructure:
    jobs:
      - iac_networking:
          context: terraform
