version: 2.1

orbs:
  terraform: circleci/terraform@3.0.0

workflows:
  iac_networking:
    jobs:
      - terraform/init:
          checkout: true
          context: terraform
          path: networking
      - terraform/fmt:
          checkout: true
          context: terraform
          path: networking
          requires:
            - terraform/init
